openapi: 3.0.3
info:
  title: 2023-BBE-1-G2_JARDHotels API
  version: '1.0'
  description: |
    The 2023-BBE-1-G1_HotelResources API. 
    Credentials:
      Admin → admin admin |
      Manager → ana456 password10 |
      Guest → jdoe jdoe123 |
      Guest → antonio789 password3 | 
      Guest → juan123 password1
servers:
  - url: '/'
    description: Localhost

paths:
  /hotels/hotel/search:
    $ref: 'api/Hotel.yml#/search'
  /hotels/hotel:
    $ref: 'api/Hotel.yml#/default'
  /hotels/hotelDoor:
    $ref: 'api/Hotel.yml#/hotelDoor'
  /hotels/filter:
    $ref: 'api/Hotel.yml#/filter'
  /hotels/touristicPlaces:
    $ref: 'api/Hotel.yml#/touristicPlaces'
  /hotels/capacity:
    $ref: 'api/Hotel.yml#/capacity'
  /hotels/profit:
    $ref: 'api/Hotel.yml#/profit'

  /rooms/room/search:
    $ref: 'api/Room.yml#/search'
  /rooms/room:
    $ref: 'api/Room.yml#/default'
  /rooms/roomDoor:
    $ref: 'api/Room.yml#/roomDoor'
  /rooms/filter:
    $ref: 'api/Room.yml#/filter'

  /persons/person/search:
    $ref: 'api/Person.yml#/search'
  /persons/person:
    $ref: 'api/Person.yml#/default'

  /guests/guest/search:
    $ref: 'api/Guest.yml#/search'
  /guests/guest:
    $ref: 'api/Guest.yml#/default'

  /bookings/booking/search:
    $ref: 'api/Booking.yml#/search'
  /bookings/booking:
    $ref: 'api/Booking.yml#/default'

  /staffs/staff/search:
    $ref: 'api/Staff.yml#/search'
  /staffs/staff:
    $ref: 'api/Staff.yml#/default'

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

security:
  - BasicAuth: []
